/**
 * Captures bird detail modal states for Scene 8 and records hex samples along
 * the crosshair animation path.
 *
 * Run:  node scripts/capture-bird.mjs
 */
import puppeteer from "puppeteer-core";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { readdirSync, writeFileSync } from "node:fs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const outDir = resolve(root, "public/product");
const BASE = process.env.BASE_URL || "http://localhost:3000";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function findChrome() {
  const base = resolve(root, "node_modules/.remotion/chrome-headless-shell");
  for (const p of readdirSync(base)) {
    try {
      const inner = resolve(base, p);
      const sub = readdirSync(inner).find((d) => d.startsWith("chrome-headless-shell"));
      if (sub) return resolve(inner, sub, "chrome-headless-shell");
    } catch {}
  }
  throw new Error("chrome not found");
}

const PATH_FRAC = [
  { f: 40, x: 0.68, y: 0.32 },
  { f: 70, x: 0.62, y: 0.38 },
  { f: 100, x: 0.55, y: 0.44 },
  { f: 130, x: 0.48, y: 0.5 },
  { f: 150, x: 0.42, y: 0.55 },
];

const browser = await puppeteer.launch({
  executablePath: findChrome(),
  headless: true,
  defaultViewport: { width: 1920, height: 1080, deviceScaleFactor: 2 },
  args: ["--no-sandbox", "--hide-scrollbars", "--force-color-profile=srgb"],
});
const page = await browser.newPage();
page.setDefaultTimeout(45000);

await page.goto(BASE, { waitUntil: "networkidle2" });
await page.waitForSelector(".grid button");
await sleep(2500);
await page.evaluate(() => {
  document.querySelectorAll("nextjs-portal").forEach((el) => {
    el.style.display = "none";
  });
});
await page.addStyleTag({ content: "nextjs-portal { display: none !important; }" });

const firstBird = await page.$(".grid button");
if (!firstBird) throw new Error("No bird card found");
await firstBird.click();

// Wait for sampling probe + "Hover on the image for color codes".
await sleep(3000);
await page.screenshot({ path: resolve(outDir, "bird-detail.png") });
console.log("bird-detail.png");

const photo = await page.$('[aria-label*="Bird photo"]');
if (!photo) throw new Error("Photo picker not found");
const box = await photo.boundingBox();
if (!box) throw new Error("Photo box not found");

const samples = [];
for (const pt of PATH_FRAC) {
  const sx = box.x + box.width * pt.x;
  const sy = box.y + box.height * pt.y;
  await page.mouse.move(sx, sy);
  await sleep(200);
  const hex = await page.evaluate(() => {
    const photo = document.querySelector('[aria-label*="Bird photo"]');
    const pill = photo?.parentElement?.querySelector('[class*="font-mono"]');
    return pill?.textContent?.trim() || null;
  });
  // Map to 1920x1080 logical viewport (deviceScaleFactor=2 screenshots are 3840 wide).
  samples.push({
    f: pt.f,
    x: Math.round((sx / box.width) * 1920 * 0.001 * box.width), // use actual screen coords at 1x
    y: Math.round(sy / 2),
    hex: hex || "#B7A07C",
  });
  // Store viewport coords at CSS pixels (1920x1080).
  samples[samples.length - 1].x = Math.round(sx);
  samples[samples.length - 1].y = Math.round(sy);
}

writeFileSync(resolve(outDir, "bird-samples.json"), JSON.stringify(samples, null, 2));

const ts = `/** Crosshair path samples for Scene 8. Regenerated by scripts/capture-bird.mjs */\nexport const BIRD_SAMPLES = ${JSON.stringify(samples, null, 2)} as const;\n`;
writeFileSync(resolve(root, "src/data/bird-samples.ts"), ts);
console.log("bird-samples.ts updated");

// Click to copy -> light toast at top.
const last = PATH_FRAC[PATH_FRAC.length - 1];
const cx = box.x + box.width * last.x;
const cy = box.y + box.height * last.y;
await page.mouse.click(cx, cy);
await sleep(700);
await page.screenshot({ path: resolve(outDir, "copy-toast.png") });
console.log("copy-toast.png");

await browser.close();
