/** Crosshair path samples for Scene 8. Regenerated by scripts/capture-bird.mjs */
export const BIRD_SAMPLES = [
  {
    "f": 40,
    "x": 572,
    "y": 199,
    "hex": "#B3AB9A"
  },
  {
    "f": 70,
    "x": 557,
    "y": 211,
    "hex": "#D7D1C8"
  },
  {
    "f": 100,
    "x": 539,
    "y": 222,
    "hex": "#D1D1D1"
  },
  {
    "f": 130,
    "x": 521,
    "y": 234,
    "hex": "#2A2530"
  },
  {
    "f": 150,
    "x": 506,
    "y": 243,
    "hex": "#9D8373"
  }
] as const;
